environment:
  matrix:
    - PYTHON: C:\Python36-x64

init:
  - SET PATH=%PYTHON%;%PATH%

install:
  - python -m pip install .
  - python -m pip install -r requirements_dev.txt

build: false

test_script:
  - python -m pytest tests

branches:
  only:
    - master

