environment:
  MINICONDA: C:\\Miniconda3-x64
  VENV_M: monkq_venv
  matrix:
    - TARGET_ARCH: "x64"
      CONDA_PY: "36"
      PY_CONDITION: "python >=3.6,<3.7"
      TA_LIB_PKG: "TA_Lib-0.4.17-cp36-cp36m-win_amd64.whl"
    - TARGET_ARCH: "x64"
      CONDA_PY: "37"
      PY_CONDITION: "python >=3.7"
      TA_LIB_PKG: "TA_Lib-0.4.17-cp37-cp37m-win_amd64.whl"
#  APPVEYOR_RDP_PASSWORD: DGC0xSBVsi5oH6XW
#services:
#  - mongodb

init:
  - SET PATH=%PYTHON%;%PATH%

cache:
  - C:\%VENV_M% -> requirements.txt, requirements_dev.txt

install:
  - mkdir C:\Users\appveyor\.conda
  - call %MINICONDA%\Scripts\activate.bat
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda no --set safety_checks disabled
  - if not exist C:\%VENV_M% conda create --prefix C:\%VENV_M% "%PY_CONDITION%"
  - conda activate C:\%VENV_M%
  - curl.exe -fsSL -o C:\%VENV_M%\%TA_LIB_PKG% https://download.lfd.uci.edu/pythonlibs/t4jqbe6o/%TA_LIB_PKG%
  - pip install C:\%VENV_M%\%TA_LIB_PKG%
  - pip install .
  - pip install -r requirements_dev.txt

build: false
test_script:
  - python -m pytest tests --mpl

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
    - master
    - dev

