language: python
os: linux
sudo: required
#services: mongodb
dist: xenial
python:
  - "3.7"
  - "3.6"
addons:
  apt:
    packages:
    - hdf5-tools
    - libhdf5-dev
branches:
  only:
  - master
  - dev
env:
  global:
    - DEPS_DIR=$HOME/dependencies
  matrix:
    - WITH_TA_LIBRARY=yes
    - TA_INCLUDE_PATH=$DEPS_DIR/include
    - LD_LIBRARY_PATH=$DEPS_DIR/lib
    - TA_LIBRARY_PATH=$DEPS_DIR/lib
cache:
  directories:
    - $DEPS_DIR

before_install:
  - if [ $WITH_TA_LIBRARY = "yes" ]; then
      ./tools/build_talib_from_source.bash $DEPS_DIR;
    fi

install:
  - pip install .
  - pip install -r requirements_dev.txt

script:
  - ./scripts/run_test.sh

after_success:
  - codecov

git:
  depth: 3