language: python
os: linux
sudo: required
dist: xenial
python:
  - "3.7"
  - "3.6"
addons:
  apt:
    packages:
    - hdf5-tools
    - libhdf5-dev
branches:
  only:
  - master
  - dev
env:
  global:
    - DEPS_DIR=$HOME/dependencies
    - PY_VENV=$DEPS_DIR/venv
    - TA_INCLUDE_PATH=$DEPS_DIR/include
    - LD_LIBRARY_PATH=$DEPS_DIR/lib
    - TA_LIBRARY_PATH=$DEPS_DIR/lib
cache:
  directories:
    - $DEPS_DIR

before_install:
  - ./scripts/build_talib_from_source.sh $DEPS_DIR

install:
  - if [ ! -d "$PY_VENV" ];then pip install virtualenv && virtualenv -p python3 $PY_VENV; fi
  - source $PY_VENV/bin/activate
  - pip install numpy && pip install .
  - pip install -r requirements_dev.txt

script:
  - ./scripts/run_test.sh

after_success:
  - codecov

git:
  depth: 3