language: python
os: linux
sudo: required
#services: mongodb
dist: xenial
python:
  - "3.7"
  - "3.6"
addons:
  apt:
    packages:
    - hdf5-tools
    - libhdf5-dev
branches:
  only:
  - master
  - dev

install:
  - pip install .
  - pip install -r requirements_dev.txt

script:
  - pytest --cov=monkq tests
  - flake8 monkq tests
  - isort --recursive --check-only monkq tests

after_success:
  - codecov

git:
  depth: 3