language: python
os: linux

services: mongodb

python:
  - "3.5"
  - "3.6"
  
branches:
  only:
  - master

install:
  - pip install .
  - pip install -r requirements_dev.txt

script: pytest tests

git:
  depth: 3